### ISSUE TITLE
ERROR    | __main__:_request:99 - Forbidden

### ISSUE THREAD

**Issue by wuzer** [little-zhong/Joker#2]
after update code, log this error
`ERROR    | __main__:_request:99 - Forbidden`

**Comment by wuzer** [comment]
also log this error

**Comment by little-zhong** [comment]
> also log this error

The new version works fine, but it requires a front-end
I don't want to waste too much of my time on this project.
<img width="2045" alt="image" src="https://github.com/user-attachments/assets/0f481244-c3cd-4c9c-aee8-a3e5445cb54f">

**Comment by wuzer** [comment]
thanks
